### ISSUE TITLE
How to update PATH in Anubis IDE?

### ISSUE THREAD

**Issue by sfl313** [AnubisLMS/IDE#18]
I try to use the "protco" command to compile the .proto file, so I could run the code with grpc.
I think I need to update the PATH so that the protoc compiler can find the plugins.
However trying a while, I still getting "protoc-gen-go: program not found or is not executable".
How could I properly update the PATH in the IDE?

**Comment by wabscale** [comment]
I believe this solves your issue: https://github.com/AnubisLMS/IDE/commit/098caacf7c17289711de17ca80cf2a801b841e34
