### ISSUE TITLE
test server url only works for 0.0.0.0:8000 (http://ide8000.anubis-lms.io)

### ISSUE THREAD

**Issue by sfl313** [AnubisLMS/IDE#19]
Hi,
I try to start multiple servers on Anubis to test my web application.
When I was trying to test just one server, I got the suggestion to use the address 0.0.0.0:8000 and test the application using http://ide8000.anubis-lms.io/.
However, if I try to use other port such as 0.0.0.0:8001, then it won't work on http://ide8001.anubis-lms.io.
Would it be able to make other port available as well?

**Comment by wabscale** [comment]
Sure no problem. I'll add that tonight.

**Comment by wabscale** [comment]
https://github.com/AnubisLMS/Anubis/commit/55eeba64371c4561d9375e3c580e30be9dd6bd0c
https://github.com/AnubisLMS/Anubis/commit/c86f0ed9773905418d08ee6c7bb74d48af5fd39e
https://github.com/AnubisLMS/Anubis/commit/d620026eab6679c2a339b7da1f5d466c6ee93a58

You now have `ide8000.anubis-lms.io`, all the way to `ide8010.anubis-lms.io` (ie: port 8000 -> 8010).
