### ISSUE TITLE
ADD python intelisense to ide

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/IDE#9]
https://open-vsx.org/extension/ms-python/python

# Adding the extension

This needs to be added to the base ([theia-base](https://github.com/AnubisLMS/IDE/tree/main/theia-base)) ide

You can see how plugins are added to the ide in the [latest.package.json](https://github.com/AnubisLMS/IDE/blob/main/theia-base/latest.package.json). You'll just need to figure out where the vsx file is on open-vsx.org, add it to the package.json, build and run the ide, and make sure it works.

# Building and Running

You can build the ide by copying the `latest.package.json` to `package.json`, then:

```shell
yarn --pure-lockfile
yarn theia build
yarn theia download:plugins
```

Then to run:

```shell
node src-gen/backend/main.js . --hostname=0.0.0.0 --port=8000
```

Make sure not to commit a `package.json`. Leave it as `latest.package.json` in your commits.

I would recommend that you do this locally and without a Cloud IDE. Node doesnt seem to work well in the IDEs.

**Comment by sp6370** [comment]
Hi @wabscale!

I don't see this assigned to anyone. Can I pick this up?

**Comment by wabscale** [comment]
Oh yeah this is done. This was actually a huge migration to get this to work. Microsoft makes it so that you have to use the non-open-source version of vscode to be able to use the full python intelisense junk. I had to rewrite everything that was from https://theia-ide.org/ to https://coder.com/docs/code-server/latest
